services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=beer_store.settings
      - PIPENV_VENV_IN_PROJECT=1

  frontend:
    build: 
      context: ./frontend/beer-store-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/beer-store-ui:/app
      - /app/node_modules
    depends_on:
      - backend