version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=beer_store.settings

  # frontend:
  #   build: ./frontend/beer-store-ui
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend/beer-store-ui:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend